media:
  input: static
  output: /alean

content:
  - name: sections
    label: Hauptseite
    path: content
    type: collection
    fields:
      - name: Title
        type: string
      - name: tagline
        type: string
      - name: image
        type: image
      - name: body
        type: rich-text
  - name: downloads
    label: Downloads
    path: content/downloads
    type: collection
    fields:
      - name: Title
        type: string
      - name: name
        type: string
      - name: isin
        type: string
      - name: waehrung
        type: string
      - name: aum
        type: string
      - name: body
        type: text