baseURL = 'https://grasgruenit.github.io/alean/'
languageCode = 'de-li'
pagination = { pagerSize = 6 }
title = 'Alean (Capital) AG'
theme= 'aplio'

[taxonomies]
  category = 'categories'
  tag = 'tags'
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
	  
[menus]
  # Main Menu
    [[menus.main]]
    name = "Dienstleistungen"
    identifier = "services"
    pageRef = ""
    weight = 2
    [[menus.main]]
    name = "Team"
    identifier = "team"
    pageRef = ""
    weight = 3
    [[menus.main]]
    name = "Fonds"
    identifier = "pages"
    pageRef = ""
    weight = 4
    [[menus.main]]
	name = "Standort"
	identifier = "contact"
	pageRef  = "/contact"
	weight = 6
	

  
[params]
  logo = "logo.png"
  logoDark = "images/logo-light.svg"
  footerDescription = "Turpis tortor nunc sed amet et faucibus vitae morbi congue sed id mauris."
  copyright = "@ 2025 Aplio. All Rights Reserved"
  contactMail = "info@example.com"
  contactNumber = "+391 35 2568 4593"
  contactAddress = "2464 Royal Ln. Mesa, New Jersey 45463"
  facebookLink= "#"
  linkedinLink= "#"
  githubLink= "#"
  behanceLink= "#"
  
[module]
  [module.hugoVersion]
    extended = false
    min = "0.145.0"
