backend:
  name: github
  repo: grasgruen.it/alean # e.g., "your-name/my-hugo-site"
  branch: main # Or master, depending on your default branch

media_folder: "static" # Folder where uploaded media will be stored
public_folder: "" # The src attribute for uploaded media will begin with this path

collections:
  - name: 'sections'
    label: 'Hauptseite'
    folder: 'content'
    create: true
    nested:
      depth: 2
    editor:
      preview: true
    fields:
      - { label: 'Tagline', name: 'tagline', widget: 'string' }
      - { label: 'Titel', name: 'Title', widget: 'string' }
      - { label: 'Bild', name: 'image', widget: 'string' }
      - { label: 'Inhalt', name: 'body', widget: 'markdown' }
    sortable_fields: ['title', 'order']
  - name: 'downloads'
    label: 'Downloads'
    folder: 'content/downloads'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'ISIN', name: 'isin', widget: 'string' }
      - { label: 'Währung', name: 'waehrung', widget: 'string' }
      - { label: 'Aum', name: 'aum', widget: 'string' }
      - { label: 'Domizil', name: 'domizil', widget: 'string' }
      - { label: 'Inhalt', name: 'body', widget: 'markdown' }
